name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the Node.js version you're working with

      - name: Install, Build, and Deploy
        run: |
          git config --global user.name "mps2209"
          git config --global user.email "manster2209@gmail.com"
          npm install
          npm run build
          npm run deploy
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CI: false # This prevents warnings during npm install
